#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/common



- name: Update apt cache
  apt:
    update_cache: yes

- name: install basic packages
  apt:
    name:
      - curl
      - git
      - vim
      - htop
    state: present

- name: Remove swap from fstab
  lineinfile:
    path: /etc/fstab
    regexp: '.*swap.*'
    state: absent

- name: Load br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: Kubernetes networking sysctl
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  loop:
    - { name: "net.bridge.bridge-nf-call-iptables", value: "1" }
    - { name: "net.bridge.bridge-nf-call-ip6tables", value: "1" }
    - { name: "net.ipv4.ip_forward", value: "1" }
